name: Daniel M. Matongo
profession: Software Developer
description: I build web applications and APIs using Ruby on Rails and Go. I also write about software development and programming. I am based in Bath, UK.
blog_name: .daniel's musings
repository: https://github.com/mmatongo/site/blob/master/
